version: '3.9'

services:
  backend_service:
    container_name: backend_container
    restart: always
    build:
      context: ../
      dockerfile: docker/Dockerfile.backend
    volumes:
      - ../backend:/backend
    ports:
      - 8000:8000
    expose:
      - 8000

  frontend_service:
    container_name: frontend_container
    restart: always
    build:
      context: ../
      dockerfile: docker/Dockerfile.frontend
    volumes:
      - ../frontend:/frontend
    ports:
      - 3000:3000
    expose:
      - 3000